from datetime import datetime
import uuid
from sqlalchemy import Column, String, DateTime, Float, ForeignKey, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.database import Base

class GuardrailEvent(Base):
    """A structured security event generated by the Guardrail Engine."""
    __tablename__ = "guardrail_events"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    trace_id = Column(UUID(as_uuid=True), ForeignKey("traces.id"), nullable=True)
    request_id = Column(String, index=True, nullable=True)
    conversation_id = Column(UUID(as_uuid=True), ForeignKey("conversations.id"), nullable=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    
    guardrail_name = Column(String, nullable=False, index=True) # e.g., PromptInjectionGuardrail
    category = Column(String, nullable=False, index=True) # e.g., INPUT, CONTEXT, OUTPUT
    action = Column(String, nullable=False) # e.g., ALLOW, BLOCK, WARN, SANITIZE, ABSTAIN
    severity = Column(String, nullable=False) # LOW, MEDIUM, HIGH, CRITICAL
    
    confidence = Column(Float, nullable=True)
    latency_ms = Column(Float, nullable=True)
    
    # Store reasoning and non-sensitive metadata. DO NOT store raw secrets here.
    metadata_json = Column(JSON, nullable=True) 
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

    trace = relationship("Trace", foreign_keys=[trace_id])
